### PR TITLE
Add m map1.4k

### PR DESCRIPTION
**Pull request by krober10nd**
* Ship m_map 1.4k with OM 
* #171

### CODE REVIEW

**Comment by WPringle** [comment]
how come so many changes coming up on this

**Review by WPringle — CHANGES_REQUESTED** [review]
Need re-post using latest Projection merged in beforehand

**Comment by krober10nd** [comment]
I merged origin/Projection in. The 110 files changed are all associated with m_map.

**Comment by krober10nd** [comment]
Need to update the blurb in the user guide to reflect this change as well.

**Comment by WPringle** [comment]
But why are all those old commits in this PR?

**Comment by krober10nd** [comment]
I had branched off and worked on something else that was not pushed to the github. 

 what matters is the files changed and you can see it's just m_map. Further, the commits will be squashed when merged in so it's moot.

**Pull request closed without merging**
