### PR TITLE
add patch smoother

### PR DESCRIPTION
**Pull request by krober10nd**
- smooths an area in the mesh preserving the patches' boundaries

### CODE REVIEW

**Comment by krober10nd** [comment]
```
smoothed_msh = mesh_patch_smoother(original_msh, poly);
```

* left before, right after 
* red line indicates user-defined polygon

Screen Shot 2020-12-15 at 8 55 47 AM

**Review by WPringle — COMMENTED** [review]
Is there a reason con is set to 5?

**Comment by krober10nd** [comment]
yea, so it doesn't turn on.

**Comment by WPringle** [comment]
I forgot we added the ds = 2 option. Cool.

**Review by WPringle — APPROVED** [review]

**Pull request merged**
