### PR TITLE
Bug fix/interp and cleaning

### PR DESCRIPTION
**Pull request by WPringle**
- Bug fix for `make_bc` call with empty varargin, e.g., when calling `inner`
- Bug fix for `ourKNNsearch` in `nanfill` option with `Griddata` (`msh.interp`)
- Bug fix for `m_map` link in `setup.sh` #277 
- Fix for `Make_offset` with constant offset (length 1 time_vector)
- Changing to implicit smoother (`ds=1`) when fix points are present inside `msh.clean`.
- Adding new stability namelist options to `Make_f15.m` fort.15 generator
- Removing `fort.15` namelists from the default setup and adding `namelist` as an argument to `Make_f15`. User provides the list of namelists desired. 
- Updating `Make_f15` help for all available input arguments.
- Adding catch for `NWS > 300` for SWAN wave coupling. In this case the `RSTIMNC` wave timestep must be supplied and this is written out into the `WTIMNC` line in `fort.15`

### CODE REVIEW

**Review by krober10nd — APPROVED** [review]
Don't see anything that looks problematic.

**Comment by krober10nd** [comment]
Just remember to delete your branch after you're done. We have a lot branch rot.

**Comment by Raam-Balaji** [comment]
Title: **Sample Code to Create fort.15 Using makefort15 with a Given fort.14 Mesh.** 

Hi, I am working on ADCIRC for a tidal simulation. I have already created the fort.14 mesh file, and I now need to generate the corresponding fort.15 file. I understand that the makefort15 subroutine can be used for this purpose.

Could you please share a sample script or example code showing how to use makefort15 to create fort.15 when fort.14 is available.

**Comment by krober10nd** [comment]
Hi, this is a pull request (that's closed). Use the issue tab to post an issue. The user guide shows how to use the makefort15 function and there's an extensive help docstring.

**Pull request merged**
