### PR TITLE
allowing user to set axis limits when plotting

### PR DESCRIPTION
**Pull request by krober10nd**
* User can set the axis limits with a kwarg `axis_limits` which over rides the default mesh extents.
```
plot(m,'type','tri','proj','lamb','axis_limits',[164, 178; -48 -40]);
```

### CODE REVIEW

**Comment by krober10nd** [comment]
@WPringle check out `test_plotting` didn't have much time to work on this today but we should have a routine that goes through the majority of combinations for plotting and visualize them to make sure it makes sense. Can't really automatically do this...

**Comment by krober10nd** [comment]
I'll wait for #221 to get merged and then rebase this before testing. Although probably should expand testing to all combinations of plotting as there some untested configurations.

**Comment by WPringle** [comment]
> @WPringle check out `test_plotting` didn't have much time to work on this today but we should have a routine that goes through the majority of combinations for plotting and visualize them to make sure it makes sense. Can't really automatically do this...

yeah that's funny how it prompts you to agree that it "looks right?". I wonder if you could count pixels or something silly like that.

**Comment by krober10nd** [comment]
The only way I think to test plotting off the top of my head would be to have a bunch of reference images and compute the spatial correlation between the images. However, this is overkill imo.

**Comment by krober10nd** [comment]
I think this fine to go for now. The testing of the plotting just runs through some common configurations to ensure some configuration doesn't break as we add future codes (labels, ticks, titles, colorbars, log options, etc.).

**Comment by WPringle** [comment]
Made some small corrections to the other tests as shown in the commit.

For the plotting test some of those options don't really work together (e..g, 'trinotri') but maybe it's good to know it doesn't error?

**Comment by krober10nd** [comment]
Yea, basically the idea is to test the API and make sure there's no failure. Perhaps in the future combinations of options that don't make sense would result in some feedback for the user.

**Review by WPringle — APPROVED** [review]

**Pull request merged**
