### PR TITLE
Adding a bash script that downloads m_map and the basic datasets

### PR DESCRIPTION
**Pull request by WPringle**
adding in the setup.sh script and changing README to fit

### CODE REVIEW

**Comment by krober10nd** [comment]
That's a good idea. Does this also add the relevant folders to the paths? If the files are already downloaded, no point to redownload.

**Comment by krober10nd** [comment]
Could be a one command type thing to start up so no path fuddling.

**Comment by WPringle** [comment]
I think with Matlab you need to add the paths to path each time unless you set permanently within windows. The bash scripts checks if the files exist so it doesn't re-download them.

**Comment by WPringle** [comment]
I guess try it out for yourself to check on your system.

**Comment by krober10nd** [comment]
yea looks like some strange formatting issue when I try to run the script from my bash terminal
```
-bash: ./setup.sh: /bin/bash^M: bad interpreter: No such file or directory
```

file is in the directory.

**Comment by krober10nd** [comment]
Ok, I ran `dos2unix` and it fixed the issue.

**Review by krober10nd — APPROVED** [review]

**Pull request merged**
