### PR TITLE
slack link update

### PR DESCRIPTION
**Pull request by krober10nd**

### CODE REVIEW

**Comment by WPringle** [comment]
It's not showing up as anything being changed

**Comment by krober10nd** [comment]
I don't know. Brian told me it was dead so I got the latest sharing link from the slack website. Guess it's the same?

**Comment by WPringle** [comment]
Yeah I get this one: https://join.slack.com/t/oceanmesh2d/shared_invite/zt-igvr8rvo-OctG9t0QEYNyyvVr55ynUQ

**Comment by WPringle** [comment]
this PR contains no changes

**Pull request closed without merging**
