### PR TITLE
adding a logo

### PR DESCRIPTION
**Pull request by krober10nd**
#152

### CODE REVIEW

**Comment by WPringle** [comment]
I think should add the logo image to the imgs folder. And since it is logo could be useful to have a vector-based form.

**Comment by krober10nd** [comment]
okay. I think I prefer the black and white version.

**Comment by WPringle** [comment]
Here are a few candidates we have so far.
image
image
image
image
image

**Comment by krober10nd** [comment]
I like the second one from the bottom.

**Comment by WPringle** [comment]
> I like the second one from the bottom.

Yeah I was starting to like the bottom one with the lower case letters.

**Comment by krober10nd** [comment]
yea that's fine by me. bottom one it is.

**Comment by WPringle** [comment]
> yea that's fine by me. bottom one it is.

We can wait some more see if @HamishB has any example too. I also want to experiment some more.

**Comment by WPringle** [comment]
New logo idea (this is just preview I have the pdf vector image):
image

**Comment by krober10nd** [comment]
I like this a lot more.

**Comment by krober10nd** [comment]
* maybe the text could be on one line? In this case perhaps moving the globe underneath or above the text?

**Comment by krober10nd** [comment]
Also maybe could make the O the globe picture? Zach had also contemplated this.

**Comment by WPringle** [comment]
image?

**Comment by krober10nd** [comment]
Creative. I approve.

**Comment by WPringle** [comment]
Final version:
Oceanmesh_logo_white
I uploaded a few different filetypes and white or transparent background.

**Review by WPringle — APPROVED** [review]
If you happy with it then let's go with this

**Pull request merged**
