### PR TITLE
More robust mesh generation

### PR DESCRIPTION
**Pull request by krober10nd**
* This PR slightly modifies the logic inside the mesh generator with the hope to make it more robust. 
*  If the mean mesh quality decreases more than 10% between consecutive mesh generation iterations, then the generator will use the previous points from the past iteration with the higher quality and then skip the current iteration; essentially trying again. 
* If this situation happens, then in addition to the above logic, the frequency of mesh improvement cycles will delay by 10 iterations in order too give the mesh generator more time to stabilize.

### CODE REVIEW

**Comment by WPringle** [comment]
Couple of thoughts:
- What if, although unlikely, the quality decreases by 10% due to a standard iteration without mesh improvements? Then will just iterate forever. 
- In the current logic it seems to increase the improvement `imp` by 10 iterations once this decrease in quality is triggered, which would then also apply to al mesh improvement cycles thereafter as well right? (i.e., stay at `imp = 20`)

Based on these thoughts why don't we just assess the change in quality after a "mesh improvement" plus one standard iteration? Then if the quality was 10% worse than before the mesh improvement just go back to that iteration, skipping the  "mesh improvement". One implementation idea would be to make an array of iteration counts where we do "mesh improvements" before the iteration loop: so `imp_array = [imp:imp:max_it];` which we just do a logical test to see if the current iteration is in `imp_array`. Then if we find that the current "mesh improvement" cycle iteration is "bad" then remove that integer from the `imp_array`.

**Comment by krober10nd** [comment]
I think  it makes sense to check only after a mesh improvement step since that’s when  the issue occurs primarily. The drop outs in quality in some recent cases were pretty severe so maybe we could increase the threshold test to a higher value. 

I don’t have a case that fails to test it unfortunately yet

**Review by WPringle — APPROVED** [review]
I ran the test suite they ran fine. The changes do not affect the tests (rewind never triggered) so hopefully this change will only affect things in cases where it should.

**Comment by WPringle** [comment]
Did any of examples trigger the rewind?

**Comment by krober10nd** [comment]
No, none of the examples triggered it but I tested the rewind in some of them by removing the logic used to trigger it. It worked in Christopher Goody's example when the initial point set was distant in density from the edgefx field.

**Pull request merged**
