### PR TITLE
remeshing polygons preserving boundary

### PR DESCRIPTION
**Pull request by krober10nd**
* sometimes a portion of the mesh must be remeshed so that the boundary of the mesh is exactly presereved. 
* Adding a tool `msh.get_poly()` to extract a polygon from a hole in the mesh. 
* Adding `mesh2d` tools to remesh the polygon exactly.
* An example of its usage.

### CODE REVIEW

**Comment by WPringle** [comment]
Can the Example_12 work without the user clicking on plot? Would prefer that we have the option for a function input that would make the clicking unnecessary (provides the hole number), but if this function input is not used then it requires clicking/user inline input.

**Comment by krober10nd** [comment]
I knew you were going to say that.

**Comment by krober10nd** [comment]
Okay, so now by default it will extract the polygon of the extracted subdomain automatically without user clicking. If the user passes `auto=0` to the `msh.get_poly` method, then it will display the figure for you to click (for more complex non-obvious cases). 

I also expanded the patch in the example so it shows how the code takes into the OM mesh sizing function.

**Review by WPringle — APPROVED** [review]
OK this seems good. Please add the changelog before merging.

**Pull request merged**
