### PR TITLE
Mesh property mapping

### PR DESCRIPTION
**Pull request by WPringle**
Adding a msh method to map the properties of a mesh subset using an array of indices.

### CODE REVIEW

**Comment by krober10nd** [comment]
Could you provide an example and put it in Examples?

**Comment by WPringle** [comment]
Hmm, it's literally just the following procedure which is done in msh.plot:
% Extract the subdomain
[ms,ind] = ExtractSubDomain(m,bou);
% Map back mesh properties
ms = mapMeshProperties(ms,ind);

**Comment by krober10nd** [comment]
So can it now plot mesh boundaries in the subset? before that was a limitation. It would be nice to have an example that highlights these plotting capabilities a bit more clearer.

**Comment by WPringle** [comment]
> So can it now plot mesh boundaries in the subset? before that was a limitation. It would be nice to have an example that highlights these plotting capabilities a bit more clearer.

True. Yeah I'm trying an example now. I realized now that the ordering needs to be corrected.

**Comment by WPringle** [comment]
This is example of plotting bcs within NZ subset. (latest commit adds lines to Example_1_NZ.m to do this)
Note that it plots the bcs on the **full-sized mesh** so it won't look perfect for that subsetted mesh (you need to recompute the bcs for that subset for that purpose)
image

**Comment by krober10nd** [comment]
yea, this was my point above that the subset doesn't plot the boundary conditions as they are in the full-mesh.

**Comment by WPringle** [comment]
> yea, this was my point above that the subset doesn't plot the boundary conditions as they are in the full-mesh.

before it created an error, but now it does not error and plots what it can like above.

**Comment by krober10nd** [comment]
> before it created an error, but now it does not error and plots what it can like above.

yea, but these boundaries aren't the same as the full-mesh as you said so they can be quite different.

**Comment by WPringle** [comment]
> > before it created an error, but now it does not error and plots what it can like above.
> 
> yea, but these boundaries aren't the same as the full-mesh as you said so they can be quite different.

the bc nodestrings plotted are the same as on the full-mesh.

**Comment by krober10nd** [comment]
> the bc nodestrings plotted are the same as on the full-mesh.

?

Per your comment above:

> Note that it plots the bcs on the full-sized mesh so it won't look perfect for that subsetted mesh (you need to recompute the bcs for that subset for that purpose)

**Comment by WPringle** [comment]
Yeah so the point is that it is only possible to plot the bcs as they are on the full-mesh but remapped to the subset. If you want to make new bcs for the subsetted mesh you would need to use the make_bc command.

**Comment by krober10nd** [comment]
I see what you mean now by your phrase "not look perfect" (i.e., green line crossing).

**Comment by WPringle** [comment]
> I see what you mean now by your phrase "not look perfect" (i.e., green line crossing).

yeah exactly

**Comment by krober10nd** [comment]
Perhaps we can add a [changelog](https://keepachangelog.com/en/1.0.0/) on the README and start from today? This will make future versioning easier.

Other than that, I experimented with `ExtractSubdomain` and this mapping business and it appeared to work, mapped the bc and attributes correctly into the subdomain. 

1) Extract subdomains should probably be named `extract_subdomain` as this is the standard for function naming conventions. It leaves less to guess when searching for methods.

2) Might want to error out if a `bou` with NaNs is passed to `extract_subdomain` as this is stated in the README but basically no one reads.

**Comment by WPringle** [comment]
> Perhaps we can add a [changelog](https://keepachangelog.com/en/1.0.0/) on the README and start from today? This will make future versioning easier.
> 
> Other than that, I experimented with `ExtractSubdomain` and this mapping business and it appeared to work, mapped the bc and attributes correctly into the subdomain.
> 
> 1. Extract subdomains should probably be named `extract_subdomain` as this is the standard for function naming conventions. It leaves less to guess when searching for methods.
> 2. Might want to error out if a `bou` with NaNs is passed to `extract_subdomain` as this is stated in the README but basically no one reads.

The last two commits solved the issues 1) and 2) (in this order). For 1) I did the rename as you suggested. For 2) I made sure that the extract_subdomain can handle 'bou' polygons either with or without NaNs.

**Comment by WPringle** [comment]
added the changelog in the last commit

**Review by krober10nd — APPROVED** [review]

**Pull request merged**
