### PR TITLE
Multiscale meshing--mesh resolution transitions 

### PR DESCRIPTION
**Pull request by WPringle**
if sum(inside) == 0 then d_l will not exist, but it seems like it sum(inside) is zero then it doesn't use the d_l anyway so can just return then.

### CODE REVIEW

**Comment by krober10nd** [comment]
* Tries to address #118 

* For multiscale meshing with boxes that have very different minimum mesh sizes, the grade between the boxes was very sharp. This was because the outer box didn't have fine enough resolution to incorporate the fine-->coarse resolution transitions. Now, we build the initial points in the outer box based on the minimum resolution in all the boxes. 

* I realize this may have a performance impact for big domains with small nests but luckily we do block the initial point rejection. I'm still a little concerned about how this affects those workflows.

* For a grade of 0.10, this is the result I get...
Screen Shot 2020-10-10 at 8 41 47 PM

**Comment by krober10nd** [comment]
Just a thought: this may be better accomplished through bar splits to make sure the point spacing is capable near the nests.

**Comment by krober10nd** [comment]
So I added some new logic for if the ratio of the smallest minimum element size between boxes exceeds two, a sequence of bar splits are performed every 2 iterations for the first 15 meshing iterations. This increases the point density near the transition zones without having to initialize the potentially huge outer domain with fine resolution.

```
clearvars; close all; clc; 

addpath(genpath('../utilities/'))
addpath(genpath('../datasets/'))
addpath(genpath('../m_map/'))
%%
bbox = [0, 1; 0,1]; 
boubox = [0,0; 1,0; 1,1; 0,1; 0,0; NaN NaN ];
min_el = 1e3; 

gdat1 = geodata('pslg',boubox,'bbox',bbox,'h0',min_el);
fh1 = edgefx('geodata',gdat1,'g',0.35);

bbox2 = [-1, 2; -1,2]; 
boubox2 = [-1,-1; 2,-1; 2,2; -1,2; -1,-1; NaN NaN ];
min_el2 = min_el*10; 

gdat2 = geodata('pslg',boubox2,'bbox',bbox2,'h0',min_el2);
fh2 = edgefx('geodata',gdat2,'g',0.35);

mshopts = meshgen('ef',{fh2, fh1},'bou',{gdat2,gdat1},'plot_on',1,'cleanup',1);
mshopts = mshopts.build;

m = mshopts.grd; 
plot(m)
```

**Comment by WPringle** [comment]
Trying this out now. It doesn't work. The improvement strategy is never used because the increase to the quality over the two iterations is larger than the requirement. This line:
`if qual_diff < imp*0.01 && qual_diff > 0`

**Comment by krober10nd** [comment]
What doesn't work? If you find a mistake, please free feel to add a change obviously.

**Comment by WPringle** [comment]
The delete bars didn't activate when I ran your code. Anyway, this fix so far seems very problematic. I tried to make updates to it but when I ran with the outer min_el2 = 3*min_el it went to trash because it trying to delete too many close points.

**Comment by WPringle** [comment]
Check out my latest commit. I think we may need to rethink it a bit.

**Comment by krober10nd** [comment]
Ah I see. I might want to make split bars a function and then just call it and leave the improvement cycle the way it is.

**Comment by krober10nd** [comment]
Could also calculate the distance between all nearest points at the beginning and then add an extra point in between them if the distance to the nearest point is too far. And repeat this before commencing mesh generation.

**Comment by WPringle** [comment]
> Could also calculate the distance between all nearest points at the beginning and then add an extra point in between them if the distance to the nearest point is too far. And repeat this before commencing mesh generation.

Yeah, I like this idea better than messing with the improvements thing.

**Comment by krober10nd** [comment]
The other idea would be to introduce a function like this: 

```
  
 function [new_points]=split(points,fh)
 SPACING=1.5;
 % find the point closest to each point (that isn't the *same* point)
 [idx, ~] = ourKNNsearch(points',points',2);
 % the ideal spacing between points
 ideal_dst = fh(points);
 % where the dst is SPACING*ideal_dist, add a point in between
 long   = zeros(length(points)*2,1);
 lat    = zeros(length(points)*2,1);
 long(1:2:end) = points(idx(:,1),1);
 long(2:2:end) = points(idx(:,2),1);
 lat(1:2:end)  = points(idx(:,1),2);
 lat(2:2:end)  = points(idx(:,2),2);
 L = m_lldist(long,lat);
 L = L(1:2:end)*1e3;            % L = lengths in meters
 splits = L > SPACING*ideal_dst;
 disp(sum(splits))
 new_points = (points(idx(splits,1),:) + points(idx(splits,2),:))./2.0;
```

That calculates the distance between points and produces a new point if it's too far as compared to the sizing function. 

Then inside `meshgen` for each box when forming the initial points, I'd call it and append those new points on. 

Oddly however, I'm getting a lot of problems with this box configuration crossing both the equator and meridian. Not surprising...

**Comment by WPringle** [comment]
I think it is better now. I found the splitting that you introduced at the start might help to reduce those missing 1-element patches developing at the multiscale nesting region. But, overall if enough iterations are done for the meshing whether this split at the start is used or not may not make a big difference due to the mesh improvement strategies during mesh generation which add points also.

**Review by krober10nd — APPROVED** [review]
Yea, things seems to be smoother now. I ran the tests locally and everything passed.

**Pull request merged**
