### PR TITLE
Variable angle of reslope 

### PR DESCRIPTION
**Pull request by jlwoodr**
Adding variable angle of reslope 'variAOR'.

### CODE REVIEW

**Comment by krober10nd** [comment]
Thanks @jlwoodr . I just renamed the new field to something a bit more easy to remember. We're trying to consistently follow [snake case](https://en.wikipedia.org/wiki/Snake_case) in new developments.

**Comment by WPringle** [comment]
I think Line 655 should be `obj.variable_angle_of_reslope` instead of just `variable_angle_of_reslope`

**Comment by WPringle** [comment]
also, instead of doing two different inputs we could just have one  (angle_of_reslope) and it just accepts either a scalar or a vector

**Comment by krober10nd** [comment]
> also, instead of doing two different inputs we could just have one (angle_of_reslope) and it just accepts either a scalar or a vector

yea that's a good idea.

**Comment by krober10nd** [comment]
Okay, now they're one field. If the field `angle_of_reslope` has a length greater than one, then it uses each value otherwise it's assumed to be a scalar with a value of 60 degrees (which was previously the scalar default). 

I haven't tested it yet. Lets see the example @jlwoodr presents.

**Comment by WPringle** [comment]
Ok, yeah let's test it. Should be a cell or vector? (implemented as cell now)

**Comment by krober10nd** [comment]
Yea, thought the same. I was thinking a cell as perhaps you could add variable angle of reslope along the width of a particular channel too for even more control.

**Comment by WPringle** [comment]
I see, do you mean the length of a channel? Like so have a cell entry that is a vector for each point of the channel?

**Comment by krober10nd** [comment]
> I see, do you mean the length of a channel? Like so have a cell entry that is a vector for each point of the channel?

Yes, this is what I mean.

**Comment by WPringle** [comment]
Ok that seems reasonable then. Yeah just try it out with various scalar and cell inputs to make sure all the various usage cases works.

**Comment by CHLNDDEV** [comment]
@jlwoodr do you want to modify this to support instead a variable `ch` parameter?

**Comment by jlwoodr** [comment]
I am not sure yet. From what I have seen in my example, users are unlikely to see much change in channel refinement when playing only with angle_of_reslope unless extreme values are used. So maybe we should have variable 'ch' parameter? Can we just do both variable angle_of_reslope and 'ch'? I think ideally a user would have a channel width for each point along a thalweg. Then OM2D would simply place however many elements the user specifies across that width.

**Comment by jlwoodr** [comment]
After running a few more tests, I think it is necessary to have variable 'ch' if users want to change mesh resolution based on channel width. From what I have seen (at least on this relatively small test domain) 'angle_of_reslope' has very little if any noticeable effect. I will start working on a variable 'ch' soon.

**Comment by krober10nd** [comment]
When you say "channel width" you mean an underwater/submerged formation? I think this is one aspect that is often confused. The "channel" mesh size function was originally intended to densify mesh resolution nearby thalwegs under the assumption that these features were responsible for more flux into the estuary and thus would benefit from capturing more finely. 

There was some sensitivity to the tides to this mesh resolution heuristic, which was studied in one of our articles but as it remains to date, the benefit still largely remains  qualitative and not easily quantifiable. 
 

If the channel is described by the banks of the water feature, the feature size mesh sizing function already enables the user to specify the number of elements across the width of the channel.

**Comment by jlwoodr** [comment]
Keith,

Sorry for my delayed response to this. When I say "channel width" I do mean
underwater formation. I have been using the "fs" parameter to control how
many elements across the width. I guess I am just running into issues with
visibly adjusting resolution around the different channels. Maybe it is my
untrained eye, but it appears that there is no difference between the 1000
m wide channel and 2000 m. I wonder if I am just not using deep enough
channels? These are extremely wide compared to their depth.

Johnathan

**Comment by krober10nd** [comment]
> When I say "channel width" I do mean underwater formation. I have been using the "fs" parameter to control how
many elements across the width.

If you want to resolve an underwater channel the `fs` parameter will not handle that. The `fs` or feature size is for measuring the distance of the shoreline features and dividing this distance by a constant `r` to get a local mesh resolution. The shoreline width uses the passed shoreline vector(s) to estimate its width.

**Comment by krober10nd** [comment]
@jlwoodr do you intend to continue this or would you like me to close it?

**Comment by jlwoodr** [comment]
Keith,

Sorry about the late response on this, totally slipped my mind. I will
likely have to pick this back up in a few months so it is cool if you close
it.

Johnathan

**Comment by krober10nd** [comment]
No worries. I'll close this for now. Let me know when you're back into this! Cheers.

**Pull request closed without merging**
