### PR TITLE
Smallest Edgefunction Value

### PR DESCRIPTION
**Pull request by cblakely97**
I added these two functions to handle a situation where an edgefunction placed "on top" (in the original code takes precedence) has a larger target edgelength than an edgefunction "below." This simply loops through the edgefunctions and places the smallest value "on top" so that it takes precedence during the mesh generation process.

### CODE REVIEW

**Comment by krober10nd** [comment]
could you provide a minimal working example of this being used? is this the `smooth_inner` William alluded to in #111 ?

**Comment by krober10nd** [comment]
also it looks like you're 150 commits behind the main branch! could you update that and then provide the example?

**Comment by cblakely97** [comment]
This is what William mentioned in [#111](https://github.com/CHLNDDEV/OceanMesh2D/issues/111). He asked me to make a pull request. I only wrote these to solve a fairly specific problem that we were having with layered edgefunctions. I will go back and double check the commits then make a simple example. It is so far behind because it has not been used since at least February and I have since started using the main branch again.

**Comment by krober10nd** [comment]
it sounds to me that this is basically computing the minimum of all sizing functions so you're essentially overloading the `min` operator for the `edgefx` class. I see how it could be useful.

**Comment by krober10nd** [comment]
so basically what we could do following your code: before calling what we call `smooth_outer` in `meshgen` compute the minimum of all supplied `edgefx` class objects. I would prefer not to `inpoly` over `polyshape` to determine which points are in which sizing function.  This would remove the MATLAB version dependency that `polyshape` creates.

**Comment by cblakely97** [comment]
Yeah as I mentioned I wrote this for a fairly specific problem Marite and I were having. I did not really intend it to become a long term solution or to necessarily be added to the master. Looking at it 9 months after I wrote it I can see tons of things I would change to make it better. If you would like I can modify it to remove polyshape or if you would prefer to modify it yourself or make a new function altogether that is fine. Just let me know!

**Comment by WPringle** [comment]
Yeah, what you said make sense @krober10nd 

So @cblakely97, are lines 65 to 118 are just smooth_outer or you did modify something critical?

**Comment by krober10nd** [comment]
okay, I'm fine with you taking a shot at it. I think it should be by default though. For instance, in the case that the user builds a single mesh with a single `edgefx`, the computed minimum `edgefx` is used to mesh. However, when we pass a cell-array to `meshgen`, the computed minimum *is not* currently computed and this can lead to some sharp transitions on the borders (I guess).

**Comment by cblakely97** [comment]
I copied smooth_outer over directly. Not sure why I did not just use it as a function but it is the same.

**Comment by cblakely97** [comment]
Actually looking closer I must have used an old version of smooth_outer, not the most recent one.

**Comment by WPringle** [comment]
> okay, I'm fine with you taking a shot at it. I think it should be by default though. For instance, in the case that the user builds a single mesh with a single `edgefx`, the computed minimum `edgefx` is used to mesh. However, when we pass a cell-array to `meshgen`, the computed minimum _is not_ currently computed and this can lead to some sharp transitions on the borders (I guess).

Yes I agree, it's not a specific problem it is really a generalized form of the minimum edgefx. In the conceptual design of the multiple edgefxs there was an assumption that the inner would always be finer than the outer, so I always just said it was user problem to make sure of that. Nevertheless, it doesn't hurt to use this and can be useful if you only want to use a specific edge function type in the inner (e.g., distance to shoreline) but use the info (e.g. slope) from the outer elsewhere.

**Comment by krober10nd** [comment]
yep. The assumption was that all mesh sizes in the inner must be finer than any meshes sizes in outer, but I wonder how often that is violated. Thinking off the top of my head, It could be a problem if some shoreline features disappear at different minimum edge-lengths. This then might cause the distance/feature size heuristics to be quite different across the edgefx domains.

**Comment by cblakely97** [comment]
I removed the use of of polyshapes and created a simple example of edgefx_filter in use. If you need me to do anything else let me know! I was not sure if I should make a new pull request or if my new commits would update the pull request.

**Comment by WPringle** [comment]
> I removed the use of of polyshapes and created a simple example of edgefx_filter in use. If you need me to do anything else let me know! I was not sure if I should make a new pull request or if my new commits would update the pull request.

Great thanks, yes the commit updates the pull request until we merge it in.

**Comment by krober10nd** [comment]
Thanks @cblakely97, I'll take a look at this soon.

**Comment by krober10nd** [comment]
I moved your changes @cblakely97 into meshgen. They should only be activated when multiscale meshing is in use and enforce the minimum sizing function will be used to mesh with.

Please try to test and break this. Thanks.

**Comment by krober10nd** [comment]
hey @cblakely97 could you take a look at this and test it to see if it produces what you expect?

**Comment by cblakely97** [comment]
It looks good to me! I ran it with some test cases I made and the results appear to be identical to what I was getting before.

**Comment by krober10nd** [comment]
Now, lets summon William @WPringle

**Comment by zcobell** [comment]
Summon

**Comment by WPringle** [comment]
Lol, @cblakely97 what about if you upload one of your test cases into the examples folder? I can test it out and modify it to be similar in structure to the other examples.

**Comment by krober10nd** [comment]
@WPringle his example was provided here https://github.com/CHLNDDEV/OceanMesh2D/commit/34efeab97ab8fe478e7571f7656cc100dfb57d68

**Comment by WPringle** [comment]
Added the Example. Result can see higher res in Tampa Bay channel:
image
image

**Review by krober10nd — APPROVED** [review]

**Pull request merged**
