### PR TITLE
fixing the cell-averaging interp option

### PR DESCRIPTION
**Pull request by WPringle**
- unequal dx and dy in the DEM lead to problems with the FindLinearIdx routine.  So fixing this routine to make sure dx and dy can be different.
- adding the 'invert' option to turn off the DEM value inversion usually peformed to make underwater positive.

See the issue #147 that brought this to our attention. 
Here is the new result using "fixed" interp:
```
m = m.interp('Topo_Bath_100x100_WGS.nc','interp','CA','invert',0);
plot(m,'b')
demcmap([-200 -100])
```
image

original dem:
image

### CODE REVIEW

**Comment by krober10nd** [comment]
yes, this seems reasonable.

**Review by krober10nd — APPROVED** [review]

**Comment by krober10nd** [comment]
I'm not sure though about that color scheme however

**Comment by WPringle** [comment]
> I'm not sure though about that color scheme however

yeah its confusing as well since for that demcmap option it inverts the depths. Should we just remove the demcmap option in msh.plot('b')?

**Comment by krober10nd** [comment]
I think so. As most people don't have it and cmocean is free.

**Comment by WPringle** [comment]
> I think so. As most people don't have it and cmocean is free.

done

**Comment by krober10nd** [comment]
where is the commit?

**Pull request merged**
