### PR TITLE
dos2unix

### PR DESCRIPTION
**Pull request by krober10nd**
#141 

@WPringle maybe you should finally purchase a Unix machine? 👍

### CODE REVIEW

**Review by WPringle — COMMENTED** [review]
Maybe it was you on your mac lol. What about the fastsmooth etc?

**Comment by krober10nd** [comment]
how do you know about `fastsmooth` etc? I ran dos2unix on the utilities folder and nothing came up as changed.

**Comment by WPringle** [comment]
On the issue #141 Hamish was saying fastsmooth looked strange with `vi`

**Review by WPringle — APPROVED** [review]

**Comment by krober10nd** [comment]
I turned this on whenever I commit so I don't think this is necessary anymore for now. I also don't see why the user can't install vim or use a different text editor.

**Comment by WPringle** [comment]
Ok seems like instead people should just be careful themselves

**Pull request closed without merging**
