### PR TITLE
bug fixes for meshing with weirs

### PR DESCRIPTION
**Pull request by krober10nd**
-Fixed point and edges were duplicated in meshgen when building the object leading to wonky constraints. 
- There was no geodata plot routine for weirs as structs. 
- The Example_JBAY_wWeirs was missing the weirs_struct to execute correctly.

### CODE REVIEW

**Comment by krober10nd** [comment]
Just a reminder: we should add an option to control the radius of influence around the merger region.

**Comment by WPringle** [comment]
I thought that we weren't providing the data in the repo which is why we left the weirs_struct out and available at the google drive link. Nevertheless, I think its easier to include small datasets here. Any others to add?

**Comment by krober10nd** [comment]
Actually, it may make more sense to show how to create the weird_struct inside the example, so then no datasets included. What do you think?

**Comment by WPringle** [comment]
> Actually, it may make more sense to show how to create the weird_struct inside the example, so then no datasets included. What do you think?

Yeah could be ay.

**Comment by WPringle** [comment]
I added an example for Alaska to demonstrate the 0-360 gdat treatment.

**Comment by WPringle** [comment]
I also added option for the merger to control the radius around the region

**Comment by krober10nd** [comment]
Cool, I'll check it out this weekend. I have to build some patches with weirs.

**Comment by krober10nd** [comment]
So from a merge I attempted today, it seems that the units of lock_dis are not being converted correctly. A lock distance of 50/111e3 degrees produced a very large amount of free points from the boundary (far further than 50 m).

**Comment by krober10nd** [comment]
Last commit fixed the issue.

**Review by WPringle — APPROVED** [review]
I think the PR is likely good. But do we need to keep those commented lines in the extractFixedConstraints function of msh.m?

**Comment by krober10nd** [comment]
Ok, yea forgot about that code.

**Pull request merged**
