### PR TITLE
Consider inner polygons w/ high fidelity

### PR DESCRIPTION
**Pull request by krober10nd**
When meshing with the high fidelity option, consider island/inner polygons to form additional breaklines in the mesh connectivity automatically.

### CODE REVIEW

**Review by WPringle — COMMENTED** [review]
Is this `polys` cell only being used for the "high-fidelity option"?

**Comment by krober10nd** [comment]
yes

**Comment by WPringle** [comment]
Then for clarity could the `polys` construction be moved to be under the if statement on line 532:
`if obj.high_fidelity{box_num}`

**Comment by krober10nd** [comment]
> Then for clarity could the `polys` construction be moved to be under the if statement on line 532: `if obj.high_fidelity{box_num}`

okay, done.

**Comment by krober10nd** [comment]
pinging @WPringle

**Review by WPringle — APPROVED** [review]

**Pull request merged**
