### PR TITLE
Update Calc_tau0.m

### PR DESCRIPTION
**Pull request by krober10nd**
Need to determine if there's no non-zero values in the array. all only checked the first element!

### CODE REVIEW

**Review by CHLNDDEV — APPROVED** [review]

**Comment by WPringle** [comment]
Only comment I have is that a bathymetry vale of 0 is actually valid and physical. Not a big fan of this way of flagging.

**Comment by WPringle** [comment]
The way this is checked is very confusing. Should just be: all(obj.b == 0) in the parenthesis.

**Comment by krober10nd** [comment]
`all(obj.b ==0)` only checks the first value in the array, which is what the problem was in the first place.

**Comment by WPringle** [comment]
No, the problem was that the parenthesis wasn't extended to the end. I.e., the original intended was correct but was a typo.

**Comment by krober10nd** [comment]
Probably better to just have a single NaN as default value and check for isnan. As you stated, 0 is a valid bathy value.

**Comment by WPringle** [comment]
Hmm, I think searching for all bathy as zero was ok since we do initialize to be all zeros. The 'any' change is confusing but I think it is equivalent to **all(obj.b == 0)**.

**Comment by krober10nd** [comment]
ok opened a new PR to go back and fix it correctly then #106

**Pull request merged**
